### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys' for restrist_reject_flat

### ISSUE THREAD

**Issue by mdclarke** [LABSN/mnefun#157]
@Eric89GXL 

Hi Eric,

I'm getting an attribute error when trying to generate ssps in mnefun.
Tried passing None, dict(grad=1e-13, mag=1e-15), and dict() for params.flat 

Traceback (most recent call last):
  File "/storage/Maggie/sasi/sasi_mnefun.py", line 112, in <module>
    print_status=True
  File "/home/mdclarke/github/mnefun/mnefun/_mnefun.py", line 593, in do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/mdclarke/github/mnefun/mnefun/_mnefun.py", line 1966, in do_preprocessing_combined
    raw_orig)
  File "/home/mdclarke/github/mnefun/mnefun/_mnefun.py", line 1238, in _restrict_reject_flat
    use_keys = [key for key in in_.keys() if key in raw]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by Eric89GXL** [comment]
Can you reproduce this with the example file? What line needs to change/add?

**Comment by mdclarke** [comment]
Yes same error when I use the sample audvis data

SSP projectors applied...
Traceback (most recent call last):
  File "/home/mdclarke/Desktop/sasi_mnefun.py", line 105, in <module>
    print_status=True
  File "/home/mdclarke/anaconda2/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 593, in do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/mdclarke/anaconda2/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 1966, in do_preprocessing_combined
    raw_orig)
  File "/home/mdclarke/anaconda2/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 1238, in _restrict_reject_flat
    use_keys = [key for key in in_.keys() if key in raw]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by Eric89GXL** [comment]
I mean the example script:

https://github.com/LABSN/mnefun/blob/master/examples/funloc/analysis_fun.py

What line needs to be changed/added to replicate the failure?

**Comment by mdclarke** [comment]
I can reproduce error with analysis_fun.py if I add 
params.reject=None
params.flat=None

**Comment by mdclarke** [comment]
It seems to work if I pass dict() for both reject and flat

**Comment by Eric89GXL** [comment]
I guess we could support passing `None` as an alias for `dict()`. Feel free to submit a PR for `mnefun` if you think it's worth having

**Comment by mdclarke** [comment]
Thanks Eric
