### ISSUE TITLE
calc_twa_hp assertion error

### ISSUE THREAD

**Issue by nordme** [LABSN/mnefun#261]
@larsoner @drammock 

Hi Eric, 

Another issue arising from the Prek runs. This is with the new version of mnefun from last week and stable mne-python 19.

Traceback (most recent call last):
  File "prek_mnefun.py", line 157, in <module>
    print_status=True    # show status
  File "/home/nordme/.conda/envs/prek_env/lib/python3.7/site-packages/mnefun-0.1-py3.7.egg/mnefun/_mnefun.py", line 717, in do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/nordme/.conda/envs/prek_env/lib/python3.7/site-packages/mnefun-0.1-py3.7.egg/mnefun/_mnefun.py", line 993, in run_sss
    run_sss_locally(p, subjects, run_indices)
  File "/home/nordme/.conda/envs/prek_env/lib/python3.7/site-packages/mnefun-0.1-py3.7.egg/mnefun/_mnefun.py", line 1315, in run_sss_locally
    trans_to = _load_trans_to(p, subj, run_indices[si])
  File "/home/nordme/.conda/envs/prek_env/lib/python3.7/site-packages/mnefun-0.1-py3.7.egg/mnefun/_mnefun.py", line 1396, in _load_trans_to
    calc_twa_hp(p, subj, trans_to, run_indices)
  File "/home/nordme/.conda/envs/prek_env/lib/python3.7/site-packages/mnefun-0.1-py3.7.egg/mnefun/_mnefun.py", line 865, in calc_twa_hp
    assert (np.diff(ts) > 0).all()
AssertionError

Let me know what you think! Thanks!

Erica

**Comment by larsoner** [comment]
Can you upload the script and subject data to kasga? Then I'll take a look.

Or if you're analyzing over SSH we can figure out over Slack how I can remote in to look directly

**Comment by nordme** [comment]
I'll upload to kasga. Thanks!

Erica Peterson
Research Scientist
Institute for Learning and Brain Sciences
University of Washington
Box 357988
Seattle, WA 98195
(206) 685-2842
