### ISSUE TITLE
RuntimeError: Could not find any MEG or EEG channels

### ISSUE THREAD

**Issue by staulu** [LABSN/mnefun#75]
With command 
simulate_movement.py --raw spi_11m_182_raw.fif --pos spi_182.pos --dipoles simulated_dipole_activations.txt --cov simple --out spi_11m_182_simu150717_raw.fif --plot
I get the error of missing MEG channels:

-------------------------------------
Simulate raw data with head movements
-------------------------------------

Reading dipole definitions ....................... done (0.0 sec)
Loading head positions ........................... done (0.0 sec)
Loading raw data file ............................ done (0.2 sec)
Using diagonal covariance for brain noise
Setting up spherical model ....................... done (0.1 sec)
Constructing source estimate ..................... done (0.0 sec)

Provided parameters will provide approximately 2202 events
Setting up raw data simulation using 337 head positions
Setting up forward solutions
Read 1 source spaces a total of 2 active source locations
Traceback (most recent call last):
  File "/home/staulu/anaconda3/bin/simulate_movement.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/staulu/mnefun/bin/simulate_movement.py", line 267, in <module>
    run()
  File "/home/staulu/mnefun/bin/simulate_movement.py", line 198, in run
    n_jobs=n_jobs, verbose=True)
  File "<string>", line 2, in simulate_movement
  File "/home/staulu/mne-python/mne/utils.py", line 538, in verbose
    return function(*args, **kwargs)
  File "/home/staulu/mnefun/mnefun/_simulate.py", line 448, in simulate_movement
    chpi_rrs, eog_rr, ecg_rr, n_jobs)):
  File "/home/staulu/mnefun/mnefun/_simulate.py", line 129, in _make_forward_solutions
    _prep_channels(info, False, True, True, verbose=False)
  File "<string>", line 2, in _prep_channels
  File "/home/staulu/mne-python/mne/utils.py", line 538, in verbose
    return function(*args, **kwargs)
  File "/home/staulu/mne-python/mne/forward/_make_forward.py", line 283, in _prep_channels
    raise RuntimeError('Could not find any MEG or EEG channels')
RuntimeError: Could not find any MEG or EEG channels

/neuro/bin/util/show_fiff indicates that there are no obvious problems with the raw data file.

**Comment by Eric89GXL** [comment]
Well that's a weird one... are those files up on a server where I could grab them to test locally?

**Comment by staulu** [comment]
The raw data files are in folder kasga:/data05/naja/Monolinguals/spi_11m_182/ and the pos file is in kasga:/data04/maggie/data/SpeechProcessing/ForSamu/spi_182.pos

**Comment by Eric89GXL** [comment]
Cool, I'll take a look at these bugs Monday. Hopefully then the simulator will actually work for you...
