### ISSUE TITLE
head pos sanity check error

### ISSUE THREAD

**Issue by mdclarke** [LABSN/mnefun#98]
Hi @Eric89GXL,
 I'm encountering the following error (for one subj) when pushing raw files and sss script to workstation with @kambysese's data.
* Head positions from quaternion file for this subj look relatively stable. 

AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05

(mismatch 100.0%)
 x: array([[-0.971479,  0.236196, -0.02098 ],
       [ 0.193013,  0.736257, -0.648592],
       [-0.137748, -0.634143, -0.760847]])
 y: array([[-0.971414,  0.236547, -0.020009],
       [ 0.192648,  0.736266, -0.648691],
       [-0.138714, -0.634002, -0.760789]])

**Comment by Eric89GXL** [comment]
Which line is that on again? (More of the traceback if you still have it)

**Comment by mdclarke** [comment]
oops sorry, here's the full thing;

Traceback (most recent call last):
  File "/home/mdclarke/github/ilabs/bad_baby/am_tone_analysis.py", line 74, in <module>
    print_status=True
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 506, in do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 637, in push_raw_files
    calc_median_hp(p, subj, med_pos, run_indices[si])
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/mnefun-0.1-py2.7.egg/mnefun/_mnefun.py", line 586, in calc_median_hp
    m, rtol=1e-5, atol=1e-5)
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/mdclarke/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05

(mismatch 100.0%)
 x: array([[-0.971479,  0.236196, -0.02098 ],
       [ 0.193013,  0.736257, -0.648592],
       [-0.137748, -0.634143, -0.760847]])
 y: array([[-0.971414,  0.236547, -0.020009],
       [ 0.192648,  0.736266, -0.648691],
       [-0.138714, -0.634002, -0.760789]])

**Comment by Eric89GXL** [comment]
Can you see if #82 fixes it for you?
